# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  ## change this to the username you want to use
  pawan67:  
    disabled: false
    ## change this to the display name you want to use
    displayname: "Pawan Tamada"  
    ## Generate the argon 2 password hash using the following command
    ## sudo docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password 'yourpassword'
    password: "$argon2id$v=19$m=65536,t=3,p=4$6a0rvQGhmmf29NAtEk0n7w$b8wCnW7kv2D/zHkSOIMyRiCuqT68nFF1RpZWb7v130s"
    email: authelia@authelia.com
    groups:
      - admins
      - dev
...
# yamllint enable rule:line-length
