services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/audiobookshelf/config:/config
      - ${DOCKER_DATA_DIR}/audiobookshelf/metadata:/metadata
      - ${DOCKER_DATA_DIR}/audiobookshelf/audiobooks:/audiobooks
      - ${DOCKER_DATA_DIR}/audiobookshelf/podcasts:/podcasts
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`${AUDIOBOOKSHELF_HOSTNAME?}`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=letsencrypt"
      - "traefik.http.routers.audiobookshelf.middlewares=authelia@docker"
      - "homepage.group=Media"
      - "homepage.name=Audiobookshelf"
      - "homepage.icon=audiobookshelf"
      - "homepage.href=https://${AUDIOBOOKSHELF_HOSTNAME?}"
      - "homepage.description=Self-hosted audiobook and podcast server"
    profiles:
      - audiobookshelf
      - all
